// <auto-generated>




namespace Example.NavigationApp
{
    public static class Page
    {
        public static class Wizard
        {
            public const string Input1 = "/Wizard/Input1Page";

            public const string Input2 = "/Wizard/Input2Page";

            public const string Result = "/Wizard/ResultPage";

        }

        public const string Menu = "/MenuPage";

    }
}

